version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 15

  seed:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: [ "node", "src/data/seed.js" ]
    environment:
      MONGO_URI: mongodb://mongo:27017/liquiverde
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGO_URI: mongodb://mongo:27017/liquiverde
    depends_on:
      mongo:
        condition: service_healthy
      seed:
        condition: service_completed_successfully
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "8080:80"

volumes:
  mongo_data:
